language: go

matrix:
  include:
    - os: linux
      go: 1.7
    - os: osx
      go: 1.7
      
after_success:
  - test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
